# Generated by Django 5.2.1 on 2025-05-12 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='barthday',
            new_name='berthday',
        ),
    ]
