# Generated by Django 5.2.1 on 2025-05-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_barthday_user_berthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mark_as_read',
            field=models.BooleanField(default=False),
        ),
    ]
